version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hotel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: hotel_db
    ports:
      - "3306:3306"
    networks:
      - hotel-network

  app:
    build: .
    container_name: hotel_app
    restart: on-failure
    ports:
      - "4040:4040"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hotel_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
      CLOUDINARY_CLOUD_NAME: dbd3osrze
      CLOUDINARY_API_KEY: 679773826221467
      CLOUDINARY_API_SECRET: 84UvncvpRILtlDmasGoZfFzf3xU
    depends_on:
      - mysql
    networks:
      - hotel-network

networks:
  hotel-network:
    driver: bridge
